name: Deploy to CloudHub 2.0

on:
  workflow_dispatch:

jobs:
  build:
    uses: anil-cicd-org/maven-deploy-workflows-master/.github/workflows/build.yml@main
    secrets:
      MAVEN_SETTINGS_BASE64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-application

      - name: Deploy to CloudHub 2.0
        run: mvn deploy -DskipMunitTests -DmuleDeploy -Pdev
