name: Deploy to CloudHub 2.0 - DEV

on:
  workflow_dispatch:
  push:
    branches: [ main ]
#
jobs:
  build-and-deploy:
    uses: anil-cicd-org/maven-deploy-workflows-master/.github/workflows/build.yml@main
    secrets:
      MAVEN_SETTINGS_BASE64: ${{ secrets.MAVEN_SETTINGS_BASE64 }} 
    with:
      environment: DEV