name: Deploy to CloudHub 2.0

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    uses: anil-cicd-org/maven-deploy-workflows-master/.github/workflows/build.yml@main
    secrets:
      MAVEN_SETTINGS_BASE64: ${{ secrets.MAVEN_SETTINGS_BASE64 }}

  # ---------------------------
  # Deployment Job
  # ---------------------------
  deploy: 
    needs: build   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up OpenJDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.9.6'

    - name: Inject Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-application

    - name: Deploy to CloudHub 2.0
      run: |
        mvn deploy -DskipMunitTests -DmuleDeploy -Pdev
